### ISSUE TITLE
Not receiving push notifications on iOS 10

### ISSUE THREAD

**Issue by PieterVO** [zendesk/sunshine-conversations-ios-rich-notifications#5]
I'm receiving the push notifications on devices that run on iOS 9 or older. But not on iOS 10.
I implemented everything that is needed to receive push notifications on iOS 10.
The problem probably lies with your server. You can check the comment of Stanley on this StackOverflow: http://stackoverflow.com/questions/39532953/push-notifications-not-being-received-on-ios-10-but-working-on-ios-9-and-before#comment66704962_39618207

**Comment by mspensieri** [comment]
Hey @PieterVO thanks for the report. I don't think the issue is with our server since I can correctly receive push notifications on iOS 10. 

![img_0140](https://cloud.githubusercontent.com/assets/2286852/20397405/99dc33e6-acb7-11e6-8143-26df2519ed19.PNG)


The SO comment you reference is specifically about silent notifications without `aps` or `alert` keys. For a Smooch notification, the `aps` field is always included with `content-available: 1`, and message notifications will also include an `alert` field with the message text.

To help debug this issue, could you verify the following:

1. Make sure "Push Notifications" is configured as ON in your project capabilities
![screen shot 2016-11-17 at 10 52 24 am](https://cloud.githubusercontent.com/assets/2286852/20396365/fb5b33a0-acb3-11e6-8ed5-bbc9af082b8c.png)
2. Check that on app startup on your iOS 10 device, there is a debug log in the Xcode console that looks like this: `<SMOOCH::INFO> Push token successfully uploaded : xyz`
3. If you set `enableAppDelegateSwizzling` to false on your `SKTSettings` object, make sure that you've followed the steps outlined in the [API documentation](http://docs.smooch.io/api/ios/Classes/SKTSettings.html#//api/name/enableAppDelegateSwizzling) for that method
4. Check in the top right hand corner of the Smooch dashboard to see if there are any alerts related to push notification errors

**Comment by PieterVO** [comment]
The issue resolved itself :) thank you anyway!

**Comment by mspensieri** [comment]
Great! 😄

**Comment by sagar-seth** [comment]
@PieterVO : I am facing similar issue. How did the issue resolve itself. We are seeing push notifications on iOS only when the app is launched. I do not see notifications when the app is backgrounded. Is there something I am missing? I followed all the steps listed on smooch iOS integration page but no luck. Will appreciate if someone can assist me. I did see an alert in the dashboards though. Some code 8 returned from Apple.

**Comment by mspensieri** [comment]
@sagar-seth Error code 8 means that the certificate you've uploaded to Smooch doesn't match the provisioning profile of the app you are trying to send to. The most common reason for this is if you are using a production certificate for a development build of your app, or vice versa.

**Comment by sagar-seth** [comment]
@mspensieri : Thanks for the response. We resolved that yesterday. What do you think is the issue with notifications not showing up when app is backgrounded?

**Comment by mspensieri** [comment]
@sagar-seth I'm not sure I understand your question. If you were receiving error code 8, then that would be the reason why notifications don't show when the app is in the background.

I'd suggest to contact our customer success team for assistance as GitHub issues are typically reserved for bug reports only and not general help requests
